### ISSUE TITLE
Warning about path to the parent when running the tests

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#116]
When running `http-minimal` module I noticed warning about path to the parent

```
15:17:21.961 INFO  Running command: mvn install -Dcheckstyle.skip -DskipTests=true -DskipITs=true -pl .
... 
15:17:29.448 INFO  [app] [WARNING] 'parent.relativePath' of POM io.quarkus.ts.qe:http-minimum:1.0.0-SNAPSHOT 
  (/Users/rsvoboda/git/quarkus-test-suite/http/http-minimum/target/app/pom.xml) 
  points at io.quarkus.ts.qe:http-minimum instead of io.quarkus.ts.qe:parent, 
  please verify your project structure @ line 4, column 13
```

The warning is imho because the app is copied into target directory and from there it points two levels up, should be pointing 4 levels up to behave correctly.

I wonder if the `<relativePath>../..</relativePath>` is really needed.

**Comment by rsvoboda** [comment]
@Sgitario can we drop `<relativePath>../..</relativePath>` from pom.xml files?

**Comment by Sgitario** [comment]
I think we can't. See https://github.com/quarkus-qe/quarkus-test-framework/blob/fb6c1dca171a9e92314a5b2564e9dbdf3337a16f/quarkus-test-core/src/main/java/io/quarkus/test/utils/MavenUtils.java#L62.

**Comment by rsvoboda** [comment]
So we won't get rid of the warning? Maybe some pom manipulation when the project gets copied to `target` directory?

**Comment by Sgitario** [comment]
> So we won't get rid of the warning? Maybe some pom manipulation when the project gets copied to `target` directory?

Yep, that makes sense to me.

**Comment by Sgitario** [comment]
@rsvoboda I can't reproduce this issue... can you help to figure out how can we get those warnings?

**Comment by rsvoboda** [comment]
same for me, tried to nuke `~/.m2/repository/io/quarkus/ts/` and execute `mvn clean verify -pl http/http-minimum` but didn't see the warning. Closing.
