### ISSUE TITLE
Testsuite gets stuck for 5 minutes when the tested application misbehaves

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#117]
Testsuite gets stuck when the tested application misbehaves like in case of https://github.com/rsvoboda/quarkus-test-suite/tree/many-extensions

```
git clone https://github.com/rsvoboda/quarkus-test-suite
cd quarkus-test-suite
git checkout many-extensions
mvn clean verify  -pl super-size/many-extensions
```

Just copied stuff from http-minimal and added extensions from https://github.com/quarkus-qe/beefy-scenarios/blob/main/003-quarkus-many-extensions/pom.xml. Intentionally didn't add content from application.properties.

I think there should be quicker fail for "baremetal" applications by default.
I know one can tune timeouts, but the default should be more fail fast friendly for the "baremetal" env.

What I see is:
```
[INFO] Running io.quarkus.ts.http.minimum.DevModeHttpMinimumIT
15:26:18.836 INFO  [app] Initialize service
...
15:26:43.038 INFO  [app] 2021-07-23 15:26:40,320 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.0.Final
...
15:36:19.468 WARNING [app] Service didn't start in PT5M minutes
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 300.218 s <<< FAILURE! - in io.quarkus.ts.http.minimum.HttpMinimumIT
```

**Comment by Sgitario** [comment]
This should have been improved when using 0.0.4 of the test framework. But I could not verify the exact scenario you described. Can you confirm that this is working fine using 0.0.4 now? You can use the branch from https://github.com/quarkus-qe/quarkus-test-suite/pull/136 .

**Comment by rsvoboda** [comment]
Checked with current main of the TS / 0.0.5 of the framework and still the timeout is 5 minutes.

At least I see the stacktrace and can Ctrl+C, but still would be better to have faster fail.

Running `mvn clean verify  -pl super-size/many-extensions` with these modifications:
```diff
--- a/super-size/many-extensions/src/main/resources/application.properties
+++ b/super-size/many-extensions/src/main/resources/application.properties
@@ -5,6 +5,6 @@ quarkus.http.root-path=/api
 %ServerlessExtensionDockerBuildStrategyOpenShiftManyExtensionsIT.quarkus.kubernetes.deployment-target=knative
 %ServerlessExtensionDockerBuildStrategyOpenShiftManyExtensionsIT.quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000

-quarkus.artemis.url=foo
-quarkus.oidc.auth-server-url=https://localhost:8180/auth/realms/quarkus
-quarkus.oidc.client-id=quarkus-app
\ No newline at end of file
+#quarkus.artemis.url=foo
+#quarkus.oidc.auth-server-url=https://localhost:8180/auth/realms/quarkus
+#quarkus.oidc.client-id=quarkus-app
\ No newline at end of file
```

**Comment by Sgitario** [comment]
> mvn clean verify -pl super-size/many-extensions

I see now.

I will update the test framework to detect the line `Attempting to start live reload endpoint to recover from previous Quarkus startup failure`. Therefore, the app will fail once this line is in the logs.
