### ISSUE TITLE
Enhance readme to add more info about the framework and how to run native mode / against OpenShift, Kubernetes

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#118]
Enhance readme of the TS to add more info about the framework and how to run native mode

https://github.com/quarkus-qe/quarkus-test-framework#readme
https://github.com/quarkus-qe/quarkus-test-framework#native

The details need to be at the top

Current one-liner (https://github.com/quarkus-qe/quarkus-test-suite#test-framework) is not sufficiently visible and strong on the message.

Add details how to run against OpenShift, Kubernetes.

**Comment by rsvoboda** [comment]
One thing I miss even in the framework readme is how to tune the config for native execution

 - How to use GraalVM instead of Mandrel
 - How to use native-image on my local path, not the docker on
   - I'm on macOS and I can't execute Linux binaries

**Comment by rsvoboda** [comment]
@pjgg / @kshpak I've hit this again. we need simple how to run stuff directly in the readme

**Comment by fedinskiy** [comment]
@rsvoboda did https://github.com/quarkus-qe/quarkus-test-suite/pull/389 solve your problems? If not, then which topics should be covered?

**Comment by rsvoboda** [comment]
Yes, I'm happy with https://github.com/quarkus-qe/quarkus-test-suite/pull/389 changes, closing.
