### ISSUE TITLE
FIPS support for Infinispan-grpc-kafka module

### ISSUE THREAD

**Issue by gtroitsk** [quarkus-qe/quarkus-test-suite#1367]
To test this module on FIPS compliant machines , we must test it on OpenJDK 17 by RedHat and using PKCS12 keystore, please see [RHEL ticket](https://issues.redhat.com/browse/RHELPLAN-110420). Using another FIPS compliant keystore is not possible. So, for example, BCFIPS provider cannot be used because we are limited by using Docker containers and the [workaround](https://issues.redhat.com/browse/QUARKUS-2036?focusedId=22655342&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22655342) is not working.
I set the [configuration](https://github.com/gtroitsk/quarkus-test-suite/commit/71f5eec166016a8492c3e3620cd196a7b2626311) as does the DataGrid QE team. The problem is that the InfinispanKafkaSaslIT test fails with Kafka exception:

```
08:16:26,485 INFO  [app] 08:16:26,266 [Consumer clientId=consumer-test-consumer-1, groupId=test-consumer] Error connecting to node localhost:32942 (id: -1 rack: null): java.io.IOException: Channel could not be created for socket java.nio.channels.SocketChannel[closed]
08:16:26,485 INFO  [app]        at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:348)
08:16:26,485 INFO  [app]        at org.apache.kafka.common.network.Selector.registerChannel(Selector.java:329)
08:16:26,485 INFO  [app]        at org.apache.kafka.common.network.Selector.connect(Selector.java:256)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1032)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1203)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1091)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:569)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:499)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:531)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1288)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1247)
08:16:26,485 INFO  [app]        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1227)
08:16:26,485 INFO  [app]        at io.quarkus.ts.messaging.infinispan.grpc.kafka.quickstart.KafkaEndpoint.lambda$initialize$1(KafkaEndpoint.java:29)
08:16:26,485 INFO  [app]        at java.base/java.lang.Thread.run(Thread.java:833)
08:16:26,485 INFO  [app] Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
08:16:26,485 INFO  [app]        at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:239)
08:16:26,486 INFO  [app]        at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:338)
08:16:26,486 INFO  [app]        ... 20 more
08:16:26,486 INFO  [app] Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
08:16:26,486 INFO  [app] Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to create SaslClient with mechanism PLAIN
08:16:26,486 INFO  [app] 08:16:26,266 [Consumer clientId=consumer-test-consumer-1, groupId=test-consumer] Bootstrap broker localhost:32942 (id: -1 rack: null) disconnected
08:16:47,918 INFO  [app] Service stopped (Quarkus JVM mode)
```

Reproducer:

```
git clone git@github.com:gtroitsk/quarkus-test-suite.git
cd quarkus-test-suite/messaging/infinispan-grpc-kafka/
git switch infinispan-pkcs12-fips
export JAVA_HOME="/qa/tools/opt/x86_64/openjdk17_last/"
PATH=/qa/tools/opt/x86_64/openjdk17_last/bin:$PATH
mvn clean verify -Dit.test=InfinispanKafkaSaslIT
```

**Comment by michalvavrik** [comment]
I fixed this.

**Comment by marnix** [comment]
For the record, May 11-20, 2024, I see probably-related PRs #1790, #1791, #1792, #1795, #1797, #1798, #1801, all from @michalvavrik.

**Comment by marnix** [comment]
@michalvavrik Not sure what the 👎 reaction on my previous comment means?

As background, we have a similar issue.  (Specifically, using BCFIPS+BCJSSE security providers but not SunSASL, we get `org.apache.kafka.common.errors.SaslAuthenticationException: Failed to create SaslClient with mechanism PLAIN`.)  So I saw your "I fixed this", without any indication of the actual changes.  So I tried to find back the actual changes that "fixed this", and documented them (for myself, for my colleagues, and for the world).

If you have details about what you changed, or a correction to my comment, or some hint about what could be causing the observed behavior, then we would very much appreciate it!

**Comment by michalvavrik** [comment]
> @michalvavrik Not sure what the 👎 reaction on my previous comment means?

I though only bots can write such a comments (or AI-helped individuals), so I gave thumbs down, nothing personal. Of these PRs you linked only https://github.com/quarkus-qe/quarkus-test-suite/pull/1792 is related.

> As background, we have a similar issue. (Specifically, using BCFIPS+BCJSSE security providers but not SunSASL, we get org.apache.kafka.common.errors.SaslAuthenticationException: Failed to create SaslClient with mechanism PLAIN.) So I saw your "I fixed this", without any indication of the actual changes. So I tried to find back the actual changes that "fixed this", and documented them (for myself, for my colleagues, and for the world).

Regarding fixing this issue, it was about using supported auth mechanism in FIPS-enabled environment. We switched to SCRAM-SHA-512 which did the trick https://github.com/quarkus-qe/quarkus-test-framework/blob/0f082e106cbab04fcc8f601589d31ae2d26b71ff/quarkus-test-service-kafka/src/main/java/io/quarkus/test/services/containers/StrimziKafkaContainerManagedResource.java#L156. The plain mechanism will never work.
