### ISSUE TITLE
Docs: Unable to run just one test case using `-Dtest=ABC`

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#142]
Unable to run just one test case using `-Dtest=ABC`

I can run the test using `-Dit.test=ABC`, but I think people are used to do just `-Dtest=ABC` aka surefire way.

@Sgitario, I was wondering if TS / failsafe plugin can give some warning to remind people to use `-Dit.test=ABC` instead of`-Dtest=ABC`?

Command examples:
```
mvn clean verify  -pl http/http-minimum -Dtest=io.quarkus.ts.http.minimum.HttpMinimumIT
  vs.
mvn clean verify  -pl http/http-minimum -Dit.test=io.quarkus.ts.http.minimum.HttpMinimumIT
```

**Comment by Sgitario** [comment]
As far I see it, people should know that `-Dtest` is for surefire tests and the other for failsafe. 
Moreover, I realised that the surefire plugin was not configured in the test suite, so I configured Maven to allow us to run surefire tests too.

**Comment by michalvavrik** [comment]
> As far I see it, people should know that `-Dtest` is for surefire tests and the other for failsafe

+1 

if developer don't know respective plugin for `-Dtest` and `-Dit.test`, then they are having wonderful opportunity to learn. also it is documented how to run `ABC` test here https://github.com/quarkus-qe/quarkus-test-suite#how-to-run-quarkus-test-suite
