### ISSUE TITLE
Docs: Effective way to investigate test failures

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#145]
When working on migration of "many extensions" scenario I had to investigate failure with the latest Quarkus main, Quarkus 2.1.0.Final was working fine.

In BeefyTS I can run the module in dev mode (as it is vanilla Quarkus app) and experiment , but in this TS I had much longer turnaround cycle, in the end I had to add `Thread.sleep` into the test to be able to play a bit more with the application.

When I realized the problem is in some extension or combination of extensions I was struggling for the second time. Adding / Removing extensions in vanilla Quarkus app with dev mode is so seamless, just edit the pom.xml, refresh browser window. With this TS it's more cumbersome, no dev mode, longer cycle to get feedback. I ended up with standalone Quarkus app and I copied the files from the module and started experimenting with dev mode.

Experience with investigation using this TS is worse than with BeefyTS.

We should start thinking about more effective ways to investigate test failures, how to prepare the standalone app.
I really miss the dev mode ability.

**Comment by rsvoboda** [comment]
so after talking with @Sgitario dev mode works too, e.g. `mvn clean quarkus:dev  -pl http/http-minimum`

I didn't realize this is possible out of the box, I though because the framework does the compose during the test execution I can't do dev mode easily, but I didn't try properly -:)

Keeping this open to enhance the documentation to highlight this efficiency tip.

**Comment by michalvavrik** [comment]
I'll take care in week 19/2023.
