### ISSUE TITLE
Missing coverage of a few RHBQ supported extensions

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#157]
We have few extensions that miss coverage in this TS.

 - quarkus-cache: https://github.com/quarkus-qe/quarkus-test-suite/issues/165
 - quarkus-logging-json: https://github.com/quarkus-qe/quarkus-test-suite/issues/168
 - quarkus-rest-client-jaxb: https://github.com/quarkus-qe/quarkus-test-suite/issues/170
 - quarkus-rest-client-jsonb: https://github.com/quarkus-qe/quarkus-test-suite/issues/170
 - quarkus-spring-boot-properties: https://github.com/quarkus-qe/quarkus-test-suite/issues/172
 - quarkus-spring-cache: https://github.com/quarkus-qe/quarkus-test-suite/issues/179
 - quarkus-spring-cloud-config-client: https://github.com/quarkus-qe/quarkus-test-suite/issues/184
 - quarkus-spring-scheduled: https://github.com/quarkus-qe/quarkus-test-suite/issues/186

Used commands:
```
mvn dependency:list -Dinclude.serverless -Dinclude.operator-scenarios -Dinclude.quarkus-cli-tests | grep ':jar:' | sort | uniq | grep io.quarkus | sed "s/.*io.quarkus/io.quarkus/g" | cut -d: -f 1-2 | uniq | grep -v io.quarkus.ts > ~/Downloads/quarkus-test-suite-extensions.txt
for i in `cat ~/Downloads/RHBQ-supported.txt`; do echo "$i ... `grep $i ~/Downloads/quarkus-test-suite-extensions.txt | wc -l`"; done | grep 0 | sort
for i in `cat ~/Downloads/RHBQ-supported.txt`; do echo "$i ... `grep $i ~/Downloads/quarkus-test-suite-extensions.txt | wc -l`"; done | grep 0 | wc -l
```

**Comment by Sgitario** [comment]
All uncovered extensions that are supported in RHBQ have been done now.
