### ISSUE TITLE
Fix test: PostgresPoolIT.checkDbPoolTurnover in JVM build

### ISSUE THREAD

**Issue by Sgitario** [quarkus-qe/quarkus-test-suite#175]
This test is randomly failing when running on JVM.

Originally, this test was not meant to be built on Native (check it out in the Beefy repository)

**Comment by Sgitario** [comment]
Example of random failure: https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/1133658704

**Comment by Sgitario** [comment]
fyi @pjgg and @fedinskiy

**Comment by fedinskiy** [comment]
@Sgitario according to linked logs the test fails on non-native(JVM build), but this is a problem anyway. I guess, the best solution would be to keep that test in beefy TS and remove it from the new one.

**Comment by Sgitario** [comment]
> @Sgitario according to linked logs the test fails on non-native(JVM build), but this is a problem anyway. I guess, the best solution would be to keep that test in beefy TS and remove it from the new one.

This test is not running on Beefy TS on Native (only in JVM) and it's not related to your migrated module (that's why I copied also to @pjgg )
In this test suite, what I did is to disable the test only on Native, so now beefy TS and this TS are behaving equally. 
But we need to figure out why is randomly failing.

**Comment by fedinskiy** [comment]
> In this test suite, what I did is to disable the test only on Native, so now beefy TS and this TS are behaving equally.
We can disable it on Native, yes, but it will fail on JVM anyway, just like it did in provided link [1]. 

To port that test from beefy to the new TS, I had to put a part of this test to a separate application, and it looks like communication over the network between the test and the application breaks some assumptions this test was based on. So we either have to change the test framework to allow injection in test classes, or move the test back to beefy.

[1] https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/1133658704

**Comment by Sgitario** [comment]
> > In this test suite, what I did is to disable the test only on Native, so now beefy TS and this TS are behaving equally.
> > We can disable it on Native, yes, but it will fail on JVM anyway, just like it did in provided link [1].
> 
> To port that test from beefy to the new TS, I had to put a part of this test to a separate application, and it looks like communication over the network between the test and the application breaks some assumptions this test was based on. So we either have to change the test framework to allow injection in test classes, or move the test back to beefy.
> 
> [1] https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/1133658704

What we need is to clearly identify the reasons why this test is randomly failing:
- I don't see how allowing injection of config values can help this test to be more consistent... Can you elaborate on this a bit further? 
- We don't need to move back anything as the test is already on Beefy.

**Comment by fedinskiy** [comment]
>I don't see how allowing injection of config values can help this test to be more consistent... Can you elaborate on this a bit further?
The test in beefy suite:
There are two classes(app and test), DbPool is directly injected into the test class. After running some tasks in the application, test send query to dbpool and receives a connection count from the dbpool directly.
The reworked test in the new TS:
There are three classes(app, test and dbpool proxy), dbpool in injected into the proxy. Query to count the number of connections is send to the proxy, and then the answer is sent back over the network. Since network has some lag, we can get a wrong connection count.
If we will be able to inject DbPool directly into the test class, we could get rid of proxy class and most network problems.

**Comment by Sgitario** [comment]
> > I don't see how allowing injection of config values can help this test to be more consistent... Can you elaborate on this a bit further?
> 
> The test in beefy suite:
> There are two classes(app and test), DbPool is directly injected into the test class. After running some tasks in the application, test send query to dbpool and receives a connection count from the dbpool directly.
> The reworked test in the new TS:
> There are three classes(app, test and dbpool proxy), dbpool in injected into the proxy. Query to count the number of connections is send to the proxy, and then the answer is sent back over the network. Since network has some lag, we can get a wrong connection count.
> If we will be able to inject DbPool directly into the test class, we could get rid of proxy class and most network problems.

I don't think that the issue is caused by some network lag, but all the events are being missing:

```
PostgresPoolIT.checkDbPoolTurnover:99 Missing 23829 events. ==> expected: <1171> but was: <0>
```

I'm checking this test...

**Comment by michalvavrik** [comment]
We don't experience the failure anymore.
