### ISSUE TITLE
Don't connect to external domains in tests

### ISSUE THREAD

**Issue by mocenas** [quarkus-qe/quarkus-test-suite#2111]
Encountered issue when connecting to external domain `example.com` and the domain started to return HTTP code 499 (Token required) on some nodes. We probably hit some kind of threshold.  This was in test `io.quarkus.ts.http.restclient.reactive#sendRequestThroughProxy` - external domain is defined [here](https://github.com/quarkus-qe/quarkus-test-suite/blob/main/http/rest-client-reactive/src/main/resources/proxy.properties#L1).

It is IMHO generally a bad idea to use external services for testing - we don't have control over them and stuff like this might happen.

EDIT: the problem with access `example.com` was actually failure in DNS resolution in our infra. 
HTTP code 499 in nginx means something like "client closed request" nothing about token.

**Comment by rsvoboda** [comment]
Please list other examples of other services so the scope is more clear.

**Comment by mocenas** [comment]
Other examples + their tests counterparts

- https://github.com/quarkus-qe/quarkus-test-suite/blob/main/properties/src/main/resources/application.properties#L31 + https://github.com/quarkus-qe/quarkus-test-suite/blob/main/properties/src/test/java/io/quarkus/ts/properties/bulk/ConfigValueIT.java#L19
- https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/cloud-events/amqp-binary/src/main/java/io/quarkus/ts/messaging/cloudevents/amqpbinary/Producer.java#L31 + https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/cloud-events/amqp-binary/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpbinary/BaseBinaryCloudEventsOverAmqpIT.java#L30
- https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/cloud-events/amqp-json/src/main/java/io/quarkus/ts/messaging/cloudevents/amqpjson/Producer.java#L39 + https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/cloud-events/amqp-json/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpjson/BaseJSONCloudEventsOverAmqpIT.java#L30
- https://github.com/quarkus-qe/quarkus-test-suite/blob/main/http/vertx-web-client/src/main/resources/application.properties#L2 + https://github.com/quarkus-qe/quarkus-test-suite/blob/main/http/vertx-web-client/src/test/resources/application.properties#L4

**Comment by mocenas** [comment]
Noting that original issue (I said some thresholding) was actually a problem with DNS resolution in our infra.

But IMHO issue still stands, using external services is IMHO bad test design.
