### ISSUE TITLE
Add coverage for quarkus-websockets-client and quarkus-websockets

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#224]
Add coverage for quarkus-websockets-client and quarkus-websockets

There is old quarkus-undertow-websockets used in `javaee-like-getting-started` and `super-size/many-extensions` but don't think we have active coverage for the functionality

**Comment by michalvavrik** [comment]
Closing as `websockets` modules provide sufficient coverage.
