### ISSUE TITLE
Conflicts between reactive and non-reactive libraries

### ISSUE THREAD

**Issue by fedinskiy** [quarkus-qe/quarkus-test-suite#297]
This time it's in many-extensions module
https://github.com/quarkus-qe/quarkus-test-suite/runs/3651178337?check_suite_focus=true
I believe underlying reason to be https://github.com/quarkusio/quarkus/issues/19875

**Comment by Sgitario** [comment]
It's caused by https://github.com/quarkusio/quarkus/commit/149d5381208fa731914a1de2ab8fc868934cfdd1.
So, spring-web dependency is not longer compatible with resteasy-classic dependencies.
I think @pjgg is going to update this module.
