### ISSUE TITLE
Investigate memory issues in native image build in `sql-app` module

### ISSUE THREAD

**Issue by jsmrcka** [quarkus-qe/quarkus-test-suite#372]
The module runs fine on bare metal with 4GB. Tested with RHBQ 2.2.3.CR5.

But when we run OpenShift scenarios with 4GB, it fails on 2.2.3.Final and later.
The failure occures during the build of a native image for a specific OpenShift test. I.e. the native build of the base application (which by default uses H2 drivers) works fine (peak memory for that case is around 3.8 GB), but the native build for certain specific tests (using specific DB drivers) fails with "out of memory". Usually, that happens for PostgreSQL, MSSQL, but sometimes also for MySQL and MariaDB.

**Comment by rsvoboda** [comment]
The first step imho is to switch H2 usage to PostgreSQL or MariaDB via testcontainers.

**Comment by rsvoboda** [comment]
In the description I miss command to reproduce the probleb and command to have successful run with just H2

**Comment by jsmrcka** [comment]
Failures happen on Jenkins nodes only. Affected jobs are being executed on VMs with 8GB of RAM, which is not enought for native build in OpenShift tests.
Tryouts with `xlarge` nodes, which employ 16 GB, proved to be successfull.

Affected jobs will be migrated to `xlarge`: https://gitlab.cee.redhat.com/quarkus-qe/jenkins-jobs/-/merge_requests/298.
