### ISSUE TITLE
`sql-app` module builds native image (unnecessarily?) every time

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#373]
`sql-app` module builds native image (unnecessarily?) every time. 

Configured properties like `quarkus.datasource.username`, `quarkus.datasource.password`, `quarkus.datasource.jdbc.url` are not fixed in build time.
See for example https://quarkus.io/guides/all-config#quarkus.datasource.username ... no lock icon at the beginning of the line.

But some of the properties like https://quarkus.io/guides/all-config#quarkus-hibernate-orm_quarkus.hibernate-orm.dialect are fixed.

AI: Talk to Hibernate experts (Sanne is the first candidate) if `quarkus.datasource. / quarkus.hibernate-orm.` need to be build time fixed.

Reproducer:
 - `mvn clean verify -Dnative -pl sql-db/sql-app -Psql-db-modules -Dquarkus.native.container-build=false`

native image is built 5 time
 - once before the tests are executed, as part of `quarkus-maven-plugin:build`
 - 4x as part of the tests - io.quarkus.ts.sqldb.sqlapp.MssqlDatabaseIT /  io.quarkus.ts.sqldb.sqlapp.Postgresql13DatabaseIT / io.quarkus.ts.sqldb.sqlapp.MariaDB10DatabaseIT / io.quarkus.ts.sqldb.sqlapp.MySqlDatabaseIT

Execution time would drop to 20%, in my case it would be from 14 minutes to 2-3 minutes. Depends if all the used properties could be runtime enabled.

**Comment by rsvoboda** [comment]
If the native binary can't be reused by the test, at least the initial native build in `quarkus-maven-plugin:build` phase should be dropped to save time.

**Comment by michalvavrik** [comment]
> AI: Talk to Hibernate experts (Sanne is the first candidate) if quarkus.datasource. / quarkus.hibernate-orm. need to be build time fixed.

IMO that's never going to happen as Agroal datasources are also CDI beans and you can't ever use runtime property to create CDI bean, you can only reduce programmatic lookup. Also you wouldn't know what drivers to register for reflection etc.

> If the native binary can't be reused by the test, at least the initial native build in quarkus-maven-plugin:build phase should be dropped to save time.

We can add `quarkus.build.skip` to modules that we know there is always used custom build for all the tests.

**Comment by michalvavrik** [comment]
We need to extend this to `sql-app-compatibility` module and check other sql modules.
