### ISSUE TITLE
DevModeOidcSecurityIT fails on FIPS-enabled machines

### ISSUE THREAD

**Issue by fedinskiy** [quarkus-qe/quarkus-test-suite#400]
According to logs[1], it's trying to deploy keycloak 15.0.2 which is not working on the FIPS-enabled machines. Looks like this class was not affected by https://github.com/quarkus-qe/quarkus-test-suite/pull/395

[1]
`14:52:16,275 INFO  [app] 14:52:14,692 Creating container for image: quay.io/keycloak/keycloak:15.0.2`

**Comment by michalvavrik** [comment]
I can see it works now in `Quarkus%20RHBQ%20Extended%20platform/job/rhbq-2.13-baremetal-ts-jvm`
