### ISSUE TITLE
Re-enable qute/multimodule

### ISSUE THREAD

**Issue by fedinskiy** [quarkus-qe/quarkus-test-suite#521]
Was disabled in https://github.com/quarkus-qe/quarkus-test-suite/pull/520 but https://github.com/quarkusio/quarkus/pull/23473 fixes this problem.Should be enabled back in several days

**Comment by rsvoboda** [comment]
Module was disabled because the #23473 PR went in and now the build throws error. Anyway, this is planned for next week in trello, now we need to process rhbq.

**Comment by rsvoboda** [comment]
Qute fix was backported to Quarkus 2.7.3.Final
