### ISSUE TITLE
Document fips-incompatible exclude in README

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#552]
https://github.com/quarkus-qe/quarkus-test-suite/pull/551 mentions `mvn -B -V -Dopenshift -Dall-modules -DexcludedGroups=fips-incompatible` command

README of the TS should be updated to reflect FIPS use case and execution command

**Comment by michalvavrik** [comment]
We need to document option to use `excludedGroups` for `fips-incompatible` as well as for other `@Tag`s.
