### ISSUE TITLE
`CommonsHeadersIT#testSessionScope` needs update

### ISSUE THREAD

**Issue by jsmrcka** [quarkus-qe/quarkus-test-suite#567]
https://github.com/quarkus-qe/quarkus-test-suite/blob/5b325d7ab40e6c00c22899cacf262c10ea46cfd0/spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/CommonsHeadersIT.java#L66

Because https://github.com/quarkusio/quarkus/issues/20003 has been closed with `won't fix`, we need to rewrite the aforementioned test.
Or decide to remove it.

**Comment by michalvavrik** [comment]
I looked at it and vote for test removal. Adding `good first issue` for removal scenario.
