### ISSUE TITLE
kafka-streams-reactive-messaging is the module that fails quite often in CI

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#570]
kafka-streams-reactive-messaging is the module that fails quite often in CI

https://github.com/quarkus-qe/quarkus-test-suite/actions

**Comment by michalvavrik** [comment]
hey @rsvoboda , yes, it still the case, but I currently have Trello card (and certain doubt I can really fix it, most likely it is not  on our side). I'd suggest there is no point of tracking it in 2 systems, so I'll go ahead and close this issue. Feel free to re-open if you prefer to keep the issue open.
