### ISSUE TITLE
Split CI native runs into more parallel runs

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#60]
Split CI native runs into more parallel runs

Waiting 4 hours for PR run is too much (https://github.com/quarkus-qe/quarkus-test-suite/pull/58)

**Comment by Sgitario** [comment]
I don't like the idea of splitting the native runs into parallel runs as won't scale well (when adding new modules).
Also, I prefer waiting 4 hours than seeing Native failures in the Daily runs and have to investigate the cause afterward.
Another alternative is to delegate into us the Native run, but this is quite risky.
Wdyt?

**Comment by rsvoboda** [comment]
Without the split into few native runs we kill efficiency for PR work. I prefer to get quick feedback loop for the PRs.
We plan to do quite a massive code coverage migration and quick CI runs are imho needed.

Adding new module is of course concern that needs to be handled as part of the PR review, PR template witch checkbox is the starting point, some additional checks in GitHub workflow using the get-all-changed-files. Maybe one day we can introduce our own github bot.
