### ISSUE TITLE
Find a proper naming strategy for docker images

### ISSUE THREAD

**Issue by fedinskiy** [quarkus-qe/quarkus-test-suite#609]
Some of the images we use in the test suite are from redhat registry, others(with the same versions) are from Docker Hub/Quay.io and it is not easy to understand, why we use some version and path in particular. It would be nice to put a bit of order in there.
See https://github.com/quarkus-qe/quarkus-test-suite/pull/608#discussion_r855147111 for context

**Comment by rsvoboda** [comment]
We need to cover both worlds, it also depends if you are using profile with registry enabled, then you have more RH based images than without the profile.
You enable the registry profile only if you are authenticated against the `registry.redhat.io`. Many RH images require authentication.
