### ISSUE TITLE
Investigate elasticsearch:7.17.2 memory issue

### ISSUE THREAD

**Issue by jsmrcka** [quarkus-qe/quarkus-test-suite#627]
Suspicious behaviour observed while using
```
docker.io/library/elasticsearch:7.17.2
```
The official image uses maximum available memory when started
without memory restrictions. That caused problems in testing environment
(Jenkins nodes) and the container kept exitting on OOM (container exit
code 137).
```
mvn clean verify -Dall-modules -pl sql-db/hibernate-fulltext-search
```
Workaround: use bitnami image `docker.io/bitnami/elasticsearch:7.17.2`, which is more conservative in memory
management and tends to constantly use ~1.3 GB.

**Comment by michalvavrik** [comment]
AI: change to `docker.io/library/elasticsearch` in your branch, copy Jenkins job (get ref from @jsmrcka on jobs where we experienced problem) and re-run. if there are still issues, lookup official docs for requirements and search for users with same issue

**Comment by jsmrcka** [comment]
The issue no longer occurs. Fixed by https://github.com/quarkus-qe/quarkus-test-suite/pull/1312. Closing.
