### ISSUE TITLE
Tests for quarkus-cli fail

### ISSUE THREAD

**Issue by fedinskiy** [quarkus-qe/quarkus-test-suite#64]
On current main (commit da63a0089266427ab713398378b91e9b5a107432 at the time of writing) all tests in quarkus-cli module fail with exception  `Caused by: java.io.IOException: Cannot run program "quarkus" (in directory "target"): error=2, No such file or directory`.

**Comment by rsvoboda** [comment]
https://github.com/quarkus-qe/quarkus-test-suite#quarkus-cli
