### ISSUE TITLE
README mentions ephemeral namespaces but there is no such section

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-test-suite#65]
https://github.com/quarkus-qe/quarkus-test-suite#running-against-red-hat-build-of-quarkus mentions ephemeral namespaces but there is no such section in the README

```
If you want to run the tests using ephemeral namespaces, go to the [Running tests in ephemeral namespaces](#running-tests-in-ephemeral-namespaces) section for more information.
```

**Comment by Sgitario** [comment]
This is a leftover. The test framework and hence the test suite is aimed to be run always using ephemeral namespaces.
I will update the readme to delete the above text.
