### ISSUE TITLE
Investigate why scenarios with MYSQL + native mode are failing with FIPS enabled

### ISSUE THREAD

**Issue by pjgg** [quarkus-qe/quarkus-test-suite#756]
Quarkus 2.7.6.Final

All MYSQL scenarios are failing in native mode with FIPS enabled.

**Comment by fedinskiy** [comment]
Identified a bug: https://github.com/quarkusio/quarkus/issues/32910.

Native mode works fine. We should add `?useSSL=false&allowPublicKeyRetrieval=True` to the end of connection string, though.

**Comment by fedinskiy** [comment]
@rsvoboda good point, fixed.
